apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jhub
    meta.helm.sh/release-namespace: jhub
  creationTimestamp: "2021-11-26T14:55:32Z"
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.2.0
    component: proxy-public
    heritage: Helm
    release: jhub
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:component: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: helm
    operation: Update
    time: "2021-11-26T14:55:32Z"
  name: proxy-public
  namespace: jhub
  resourceVersion: "47668192"
  uid: a1393b07-56d2-45c5-8f4f-a639628dea63
spec:
  clusterIP: 10.43.229.94
  clusterIPs:
  - 10.43.229.94
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30854
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    component: proxy
    release: jhub
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
